spring.application.name=PRO2-project

# P?ipojení k H2 databázi v pam?ti (pro vývoj nejrychlej?í)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate (ORM) automaticky vytvo?í/upraví tabulky podle tvých t?íd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true