spring.application.name=PRO2-project

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate (ORM) automaticky vytvo?í/upraví tabulky podle tvých t?íd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


riot.api.key=dhawhdowiuahoiuwahdawdiz
riot.api.region.account=europe
riot.api.region.summoner=eun1